### ISSUE TITLE
CPA calculations fail to set the `RMTCORE`

### ISSUE THREAD

**Issue by JPchico** [JuDFTteam/masci-tools#50]
When trying to run a CPA calculation using [aiida-kkr](https://github.com/JuDFTteam/aiida-kkr) the system fails to setup the `RMTCORE`
```
      raise TypeError('Error: array input not consistent for key {}'.format(key))
 TypeError: Error: array input not consistent for key <RMTCORE>
```

My guess is that there is a size inconsistency somewhere, here, I'm unsure if `RMTCORE` should be of `natyp` size or `naez` size.
```python
            listargs = dict([['<RBASIS>', naez], ['<RBLEFT>', nlbasis], ['<RBRIGHT>', nrbasis], ['<SHAPE>', natyp],
                             ['<ZATOM>', natyp], ['<SOCSCL>', natyp], ['<SITE>', natyp], ['<CPA-CONC>', natyp],
                             ['<KAOEZL>', nlbasis], ['<KAOEZR>', nrbasis], ['XINIPOL', natyp], ['<RMTREF>', natyp],
                             ['<RMTREFL>', nlbasis], ['<RMTREFR>', nrbasis], ['<FPRADIUS>', natyp], ['BZDIVIDE', 3],
                             ['<RBLEFT>', nrbasis], ['ZPERIODL', 3], ['<RBRIGHT>', nrbasis], ['ZPERIODR', 3],
                             ['LDAU_PARA', 5], ['CPAINFO', 2], ['<DELTAE>', 2], ['FILES', 2], ['DECIFILES', 2],
                             ['<RMTCORE>', natyp], ['<AT_SCALE_BDG>', natyp]])
            # deal with special stuff for voronoi:
            if self.__params_type == 'voronoi':
                listargs['<RMTCORE>'] = natyp
                self.update_to_voronoi()
```

**Comment by PhilippRue** [comment]
I just check in the voronoi code which uses the `RMTCORE` input and there we read it in a loop like this
```
   DO I = 1,NAEZ
        CALL IoInput('<RMTCORE>       ',UIO,I,7,IER)
         IF (IER.EQ.0) READ (UNIT=UIO,FMT=*) RMTCORE(I)
      ENDDO
```
So the array size should be `naez` instead of `natyp` which makes sense because it should be the same for different CPA atoms on the same site.

**Comment by JPchico** [comment]
@PhilippRue Thanks, indeed it makes sense. 

Then I wonder what is the source of the error? Could it be an issue in the EOS workchain itself that is just caught by masci-tools?

**Comment by JPchico** [comment]
I think the issue is indeed with the EOS workchain in aiida-kkr. Since running a single SCF calculation seems to work fine. I'll close the issue here and open another one in the kkr git instead.
