### ISSUE TITLE
Package size to large with several MB

### ISSUE THREAD

**Issue by broeder-j** [JuDFTteam/masci-tools#52]
The package size of masci-tools is quite large 5.8MB, the wheel is still ok. 
We should think about seperating the tests and datafiles from the source code.

**Comment by janssenhenning** [comment]
Done with 9e8de9211420a100bee2f7cfe45003f45c5c007b

**Comment by janssenhenning** [comment]
@broeder-j Just noticed that I forgot to actually exclude the tests directory in setup.py 🤦. But for the next release the source will be smaller
