### ISSUE TITLE
Atom names seem to be wrong

### ISSUE THREAD

**Issue by MRedies** [JuDFTteam/masci-tools#55]
This inp.xml has 4 atom species 2 Fe, 1 O, 1 Y,
[inp.zip](https://github.com/JuDFTteam/masci-tools/files/6722142/inp.zip)
it results in this banddos:
[banddos.zip](https://github.com/JuDFTteam/masci-tools/files/6722140/banddos.zip)

Then I plot them like this:
```python
with HDF5Reader('banddos.hdf') as h5reader:
   data, attributes = h5reader.read(recipe=FleurDOS)

#Plot the data
#Notice that you get the axis object of this plot is returned
#if you want to make any special additions
ax = plot_fleur_dos(data, attributes,  show_atoms='all')
```
I get 4 atom types as well, but they are all called Fe:
![image](https://user-images.githubusercontent.com/6518935/123555913-df7d7f80-d788-11eb-927c-4de5628e0e6b.png)

**Comment by janssenhenning** [comment]
Thanks for the report. That should be a relatively simple fix.
