### ISSUE TITLE
limits keyword does not work for DOS plots

### ISSUE THREAD

**Issue by MRedies** [JuDFTteam/masci-tools#57]
Following the [docu](https://masci-tools.readthedocs.io/en/latest/module_guide/code.html?highlight=plot_fleur_dos#masci_tools.vis.matplotlib_plotter.MatplotlibPlotter) I tried to do this:
![image](https://user-images.githubusercontent.com/6518935/124388372-f2410880-dce2-11eb-9e8b-7c73264b9ac5.png)
```python
#Read in data
with HDF5Reader("PBE/kpts=0003/DOS/banddos.hdf") as h5reader:
   data, attributes = h5reader.read(recipe=FleurDOS)

#Plot the data
#Notice that you get the axis object of this plot is returned
#if you want to make any special additions
ax = plot_fleur_dos(data, attributes, multiply_by_equiv_atoms=True, linewidth=1.5, limits={'x': (-5,5)})
```
The linewidth one works, but the limits one returns:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-09c6c8132087> in <module>
      6 #Notice that you get the axis object of this plot is returned
      7 #if you want to make any special additions
----> 8 ax = plot_fleur_dos(data, attributes, multiply_by_equiv_atoms=True, linewidth=1.5, limits={'x': (-5,5)})

~/.local/lib/python3.8/site-packages/masci_tools/vis/fleur.py in plot_fleur_dos(dosdata, attributes, spinpol, bokeh_plot, multiply_by_equiv_atoms, plot_keys, show_total, show_interstitial, show_sym, show_atoms, show_lresolved, key_mask, **kwargs)
    364     legend_labels, keys = np.array(legend_labels)[key_mask].tolist(), np.array(keys)[key_mask].tolist()
    365 
--> 366     kwargs = _process_dos_kwargs(keys, **kwargs)
    367 
    368     if bokeh_plot:

~/.local/lib/python3.8/site-packages/masci_tools/vis/fleur.py in _process_dos_kwargs(ordered_keys, **kwargs)
    404                         new_dict[ordered_keys.index(plot_label)] = new_dict.pop(plot_label)
    405                     else:
--> 406                         raise ValueError(f'The label {plot_label} is not a valid label for the current plot')
    407             kwargs[key] = new_dict
    408     return kwargs

ValueError: The label x is not a valid label for the current plot

```

**Comment by MRedies** [comment]
Also notice that the appostrophies around x are wrong in the docu. They seem to be correct in the comment of the source, but by the time they arrive on readthedocs they are not 'x', but ‘x’, which makes copied stuff wrong. 

This might be a problem for newer users.

**Comment by janssenhenning** [comment]
@redies The documentation is now fixed All the dictionaries in the table are now put into literal blocks to avoid this character change.
I will prepare a bugfix release for the ``limits`` keyword shortly

**Comment by janssenhenning** [comment]
@MRedies This is fixed with the newest pypi release.

**Comment by MRedies** [comment]
Thank you, Hennig. I already feel bad about creating too many issues. I actually really like the masci tools

**Comment by janssenhenning** [comment]
@MRedies That's no problem and I'm happy about all reported issues (otherwise I only fix the stuff I stumble upon :D). I'm aware that the test coverage in the plotting methods is still lacking so these kind of errors can easily happen.
