### ISSUE TITLE
multiply_by_equiv_atoms=True as default

### ISSUE THREAD

**Issue by MRedies** [JuDFTteam/masci-tools#60]
Hello,
I'd like to suggest to set `multiply_by_equiv_atoms=True` as default for DOS plots, because the other one is just confusing. In some systems this isn't too important, but if you have a lot of symmetry I can distort the plot a lot.

**Comment by janssenhenning** [comment]
@MRedies Yes I think that's fair, since ``multiply_by_equiv_atoms=True`` makes the plot more consistent. I'll change it for the next release

**Comment by janssenhenning** [comment]
Closed with 239576e
