### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by janssenhenning** [JuDFTteam/masci-tools#65]
I think we should very soon create a new release, since we then could move forward with fleur interfaces to ``ase`` and ``pymatgen``. Below I post a few questions/thoughts on this:

Should this release be ``0.5.0``, since it adds new features with the inpgen IO functions?

Is there something that should still be added @PhilippRue @broeder-j ? I for example see a branch with small changes ``combime_imp_masci_tool``, which would need to be rebased/merged.
@Irratzo The constants versioning should probably also be included, right? Could you open a PR for that?

The PR #54 should be merged after the release for Jens HTC paper I think, since it has large impact on the plotting functions. And though I'm confident it breaks/changes no existing plots I would feel even more confident if we have this functionality on the develop branch for a time so that more people test it.

**Comment by Irratzo** [comment]
Hi @janssenhenning, okay, I will write the PR hopefully today (will notify). Needed to work on setup for (local) production testing first, but nearly finished with that.

**Comment by Irratzo** [comment]
Okay, I've opened the [PR](https://github.com/JuDFTteam/masci-tools/pull/66) for the KKR constants versioning. Sorry for the delay.

**Comment by PhilippRue** [comment]
@RubelMozumder can you say something about the `combime_imp_masci_tool ` branch? Should it be in the next release?

**Comment by janssenhenning** [comment]
I opened PR #67 in preparation for the release. I added a [CHANGELOG.md](../blob/Release-0.5.0/CHANGELOG.md) to document changes in the versions, since ``masci-tools`` has grown a lot :)

**Comment by janssenhenning** [comment]
@PhilippRue @broeder-j @Irratzo If no one objects I will create the new release today in the evening
