### ISSUE TITLE
Saveas doesn't support pdf

### ISSUE THREAD

**Issue by MRedies** [JuDFTteam/masci-tools#68]
The plotdos routine: 
https://masci-tools.readthedocs.io/en/latest/module_guide/code.html?highlight=plot_dos#masci_tools.vis.plot_methods.plot_dos

has a `saveas` argument, which I call with `saveas="bla.pdf"`. This results in a file called `bla.pdf.png`. This is a bit unfortunate, since often you want a pdf, rather than a png (it's a vector graphic).

**Comment by janssenhenning** [comment]
The `saveas` option only takes the filename without extension (however we could change that if it is wanted, overrriding the format if it is included in the saveas argument). To specify the  format you can pass the keyword argument `save_format` with the wanted format, i.e. `'pdf'` (You can also pass a list of formats if you need multiple different ones). Note that you can also specify additional options for saving with the `save_options` argument

You can find the information in the table
https://masci-tools.readthedocs.io/en/latest/module_guide/code.html#module-masci_tools.vis.matplotlib_plotter

**Comment by MRedies** [comment]
Ok then I was confused by the interface. In matplotlib they determine the type trough the name, but I think either way is fine.
